[package]
name = "hotcode_core"
version = "0.2.0"
edition = "2024"

[dependencies]
libloading = { workspace = true }
arc-swap = { workspace = true }
notify-debouncer-full = { workspace = true }

[lints.clippy]
needless_return = "allow"
match_like_matches_macro = "allow"

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }